### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by Behnam1369** [Kakalanp/Tip-calculator#3]
Good job @Kakalanp 
Good job @estebanmual 

I really enjoyed reviewing your project: It was amazing. 👍 
I really didn't find anything that you can improve. 

Cheers and happy coding.

**Comment by Kakalanp** [comment]
## Thank you very much! @Behnam1369 ✨ 

Your review is the type of review that encourages us to keep improving and making projects like this one! 💯
